### ISSUE TITLE
child hierarchy doesn't display in themes/*.*/views/Detail/ca_objects_detail_html.php

### ISSUE THREAD

**Issue by casual2atee** [collectiveaccess/pawtucket#12]
![screenshot1](https://cloud.githubusercontent.com/assets/7117911/14799609/024360dc-0b03-11e6-8824-a35ca1a697b1.jpg)
As I understand it. $va_child is returning as a string, not an array, in CA1.4. So when it's a string, then you CAN treat it as an array, but non-numeric indexes will be treated as 0 - meaning you're accessing the first (zero-index) char of that string. Adding var_dump confirms this. So then, how do we get the string to display all of the characters instead of just the first character?

This code returns only the first character of child_object_name

**Comment by stefankeidel** [comment]
The behavior of `get()` changed over time, so it's possible whatever theme code you're looking at was developed using a different CA version. Shouldn't be too hard to fix.

**Comment by stefankeidel** [comment]
Are you sure this is CA v1.4? The thing is if you want click-able links, you're going to need more than just the names of the child objects. Try adding the `returnWithStructure` option to that `get()` call. I'm sure that was added in v1.5, but you never know.

**Comment by casual2atee** [comment]
`# --- child hierarchy info
			$va_children = $t_object->get("ca_objects.children.preferred_labels", array('returnAsArray' => 1, 'returnAsLink' => true, 'checkAccess' => $va_access_values));
			if(sizeof($va_children) > 0){
				print "<div class='unit'><h2>"._t("Part%1", ((sizeof($va_children) > 1) ? "s" : ""))."</h2> ";
				echo implode(",", $va_children);
				print "</div>";
			}`
![screenshot1](https://cloud.githubusercontent.com/assets/7117911/14831555/e1dedd44-0bbb-11e6-9ec4-8bf1e5102ee4.jpg)
